services:
  mysql:
    image: 'mysql'
    environment:
      - 'MYSQL_DATABASE=pagamentodb'
      - 'MYSQL_PASSWORD=123'
      - 'MYSQL_ROOT_PASSWORD=123'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'